
services:
  postgres:
    image: postgres:14
    container_name: allpeople-db-docker
    restart: always
    environment:
      POSTGRES_USER: allpeople
      POSTGRES_PASSWORD: julian13
      POSTGRES_DB: loyalty_db
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: